name: Gradle Check

on:
  pull_request:
  push:
    branches:
      - master
      - main


jobs:
  build:
    strategy:
      matrix:
        os:
          - macOS-latest
          # - windows-latest
          - ubuntu-latest

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Configure gradle
        uses: gradle/gradle-build-action@v2

      - name: Configure node with npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Purs-Tidy
        run: npm install -g purs-tidy

      - name: Gradle Check
        run: ./gradlew check