name: Publish

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Configure gradle
        uses: gradle/gradle-build-action@v2

      - name: Configure node with npm
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Purs-Tidy
        run: npm install -g purs-tidy

      - name: Gradle Publish Plugin
        run: |
          VERSION=$(git describe --tags --match='v*')
          ./gradlew :publishPlugin -PintellijPublishToken="${{ secrets.INTELLIJPUBLISHTOKEN }}" -PpublishChannels=Stable -Pversion="$VERSION" 