name: Publish

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Cache gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache gradle wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlewrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradlewrapper-

      - name: Cache maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure node with npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Purs-Tidy
        run: npm install purs-tidy

      - name: Gradle Publish Plugin
        run: |
          VERSION=$(git describe --tags --match='v*')
          ./gradlew :publishPlugin -PintellijPublishToken="${{ secrets.INTELLIJPUBLISHTOKEN }}" -PpublishChannels=Stable -PideaVersion=LATEST-EAP-SNAPSHOT -Pversion="$VERSION"